In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = pd.read_csv("/content/Churn_Modelling.csv")

X = data.iloc[:,3:-1].values
#3rd to last-1
Y = data.iloc[:,-1].values
#lasrt -1  , dependent ,output , iloc pandas

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
Y

array([1, 0, 1, ..., 1, 1, 0])

In [8]:
LE1 = LabelEncoder()
#sklern label encoding - gender
X[:,2] = np.array(LE1.fit_transform(X[:,2]))

ct =ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder="passthrough")
#sklear - one hot encoding - string to binary
X = np.array(ct.fit_transform(X))

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

sc = StandardScaler()
#standardization -3 se +3 tak , x-mean/sd
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
#unit - no. of neuron
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])
ann.fit(X_train,Y_train,batch_size=32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6240 - accuracy: 0.6755
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4725 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4494 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4359 - accuracy: 0.8005
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.8116
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4181 - accuracy: 0.8146
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4126 - accuracy: 0.8200
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4070 - accuracy: 0.8241
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4008 - accuracy: 0.8235
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3931 - accura

In [10]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1,50000]])) > 0.5)


1/1 [==============================] - 0s 419ms/step
[[False]]


In [11]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = ann.predict(X_test)
y_pred

63/63 [==============================] - 0s 1ms/step


array([[0.2015431 ],
       [0.3254148 ],
       [0.17695077],
       ...,
       [0.0948815 ],
       [0.14294176],
       [0.15461487]], dtype=float32)

In [13]:
print(y_pred)
y_pred = y_pred.round()
print(y_pred)
print(np.array(Y_test).reshape(-1, 1).astype('float32'))

[[0.2015431 ]
 [0.3254148 ]
 [0.17695077]
 ...
 [0.0948815 ]
 [0.14294176]
 [0.15461487]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [1.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [14]:
y_test = np.array(Y_test).reshape(-1, 1).astype('float32')

print(f'Accuracy - {accuracy_score(y_test, y_pred)}')
print(classification_report(np.array(Y_test).reshape(-1, 1), y_pred))

Accuracy - 0.861
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.72      0.52      0.60       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000

